"""CI failure triage tool.

Finds failed CI runs (GitHub Actions, Azure Pipelines) for a PR,
extracts error logs, checks for similar failures across the repo,
and uses Claude to analyze root cause. Posts findings as a PR comment.
"""

import os
import sys

from ci_tools.bedrock import call_bedrock
from ci_tools.log_parser import extract_error_snippet
from ci_tools.providers import github_actions, azure_pipelines

PR_NUMBER = int(os.environ["PR_NUMBER"])
REPO = os.environ["REPO"]

MAX_DIFF_CHARS = 12000

PROVIDERS = [github_actions, azure_pipelines]


def analyze_with_claude(error_info, similar_failures, pr_diff, pr_number):
    """Send failure data to Claude for analysis via AWS Bedrock."""
    system_prompt = """\
You are a CI failure triage specialist. Your job is to analyze CI test failures \
and determine their root cause.

Failures may come from multiple CI systems (GitHub Actions, Azure Pipelines). \
Each job is labeled with its CI provider.

Common failure categories:
1. PR-specific: The PR's code changes directly caused the failure
2. Infrastructure/flaky: Network timeouts, runner issues, dependency install failures
3. Upstream breakage: A dependency introduced a regression
4. Pre-existing: The same failure occurs on main or other PRs (not caused by this PR)

Be concise and actionable. Use markdown formatting."""

    error_section = ""
    for info in error_info:
        provider = info.get("provider", "Unknown")
        error_section += f"\n#### [{provider}] Job: {info['job_name']}\n"
        error_section += f"**Failed step**: {info['failed_step'] or 'Unknown'}\n"
        error_section += f"```\n{info['snippet'][:4000]}\n```\n"

    if similar_failures:
        similar_section = "### Similar Failures Found\n"
        for sf in similar_failures:
            provider = sf.get("provider", "Unknown")
            source = f"PR #{sf['source_pr']}" if sf["source_pr"] else f"branch `{sf['branch']}`"
            similar_section += f"- [{provider}] **{sf['job_name']}** on {source} ({sf['created_at'][:10]}): "
            similar_section += ", ".join(sf["matching_signatures"][:3]) + "\n"
    else:
        similar_section = "### Similar Failures\nNo similar failures found in recent runs on main or other PRs.\n"

    user_prompt = f"""\
## PR #{pr_number} CI Failure Analysis (repo: {REPO})

### Failed Jobs and Error Logs
{error_section}

{similar_section}

### PR Code Changes (diff)
```diff
{pr_diff[:8000]}
```

---
Please analyze this CI failure and provide:

1. **Failure Classification**: Is this PR-specific, infrastructure/flaky, upstream, or pre-existing?
2. **Root Cause**: What is the most likely cause of the failure?
3. **Evidence**: What specific log lines or patterns support your conclusion?
4. **Relevant Code Changes**: If PR-specific, which changes in the diff likely caused it?
5. **Recommendation**: What should the PR author do next?"""

    return call_bedrock(system_prompt, user_prompt)


def format_comment(pr_number, runs, error_info, analysis, similar_failures):
    """Format the triage results as a PR comment."""
    # Run info header
    run_parts = []
    for run in runs:
        provider = run.get("provider", "Unknown")
        run_url = run.get("html_url", "")
        run_id = run.get("id", "")
        run_parts.append(f"[{provider}: {run_id}]({run_url})")
    runs_str = " | ".join(run_parts)

    created = runs[0].get("created_at", "")[:10] if runs else ""

    job_names = ", ".join(
        f"[{info.get('provider', '?')[0]}] {info['job_name']}"
        for info in error_info
    )
    job_details = ""
    for info in error_info:
        provider = info.get("provider", "Unknown")
        job_url = info.get("html_url", "")
        link = f"[{info['job_name']}]({job_url})" if job_url else info["job_name"]
        job_details += f"- [{provider}] {link} "
        job_details += f"(failed step: {info['failed_step'] or 'Unknown'})\n"

    similar_section = ""
    if similar_failures:
        similar_section = "| Provider | Job | Source | Date | Matching Errors |\n"
        similar_section += "|----------|-----|--------|------|-----------------|\n"
        for sf in similar_failures:
            provider = sf.get("provider", "?")
            source = f"PR #{sf['source_pr']}" if sf["source_pr"] else f"`{sf['branch']}`"
            sigs = ", ".join(s[:50] for s in sf["matching_signatures"][:2])
            similar_section += f"| {provider} | {sf['job_name']} | {source} | {sf['created_at'][:10]} | {sigs} |\n"
    else:
        similar_section = "No similar failures found in recent runs.\n"

    return f"""\
## CI Failure Triage Report

**Runs**: {runs_str} | **Date**: {created}

<details>
<summary><b>Failed Jobs</b>: {job_names}</summary>

{job_details}
</details>

### Analysis

{analysis}

---

<details>
<summary>Similar failures in recent runs</summary>

{similar_section}
</details>

---
_Generated by CI Triage Bot_
"""


def main():
    print(f"Triaging CI failure for PR #{PR_NUMBER} in {REPO}")

    # 1. Get PR info and diff (always via GitHub since PRs live there)
    pr_info = github_actions.get_pr_info(REPO, PR_NUMBER)
    head_ref = pr_info["head_ref"]
    print(f"PR head branch: {head_ref}")

    # 2. Collect failed runs from all available providers
    all_runs = []
    all_error_info = []
    all_similar = []

    for provider in PROVIDERS:
        if not provider.is_available():
            print(f"[{provider.PROVIDER_NAME}] Skipped (not configured)")
            continue

        print(f"[{provider.PROVIDER_NAME}] Searching for failed runs...")

        try:
            runs = provider.get_failed_runs(REPO, PR_NUMBER, head_ref)
        except Exception as e:
            print(f"[{provider.PROVIDER_NAME}] Error fetching runs: {e}")
            continue

        if not runs:
            print(f"[{provider.PROVIDER_NAME}] No failed runs found")
            continue

        run = runs[0]
        all_runs.append(run)
        print(f"[{provider.PROVIDER_NAME}] Found failed run: {run['id']}")

        try:
            failed_jobs = provider.get_failed_jobs(REPO, run["id"])
        except Exception as e:
            print(f"[{provider.PROVIDER_NAME}] Error fetching jobs: {e}")
            continue

        if not failed_jobs:
            print(f"[{provider.PROVIDER_NAME}] No failed jobs in run")
            continue

        print(f"[{provider.PROVIDER_NAME}] Found {len(failed_jobs)} failed job(s)")

        for job in failed_jobs:
            print(f"  Fetching logs for: {job['name']}")
            raw_log = provider.get_job_logs(REPO, job["id"], _log_id=job.get("_log_id"))
            snippet = extract_error_snippet(raw_log, job.get("failed_step"))
            all_error_info.append({
                "job_name": job["name"],
                "job_id": job["id"],
                "failed_step": job.get("failed_step"),
                "snippet": snippet,
                "html_url": job.get("html_url"),
                "provider": provider.PROVIDER_NAME,
            })

        # Search for similar failures
        print(f"[{provider.PROVIDER_NAME}] Searching for similar failures...")
        try:
            similar = provider.find_similar_failures(REPO, all_error_info, PR_NUMBER)
            all_similar.extend(similar)
            print(f"[{provider.PROVIDER_NAME}] Found {len(similar)} similar failure(s)")
        except Exception as e:
            print(f"[{provider.PROVIDER_NAME}] Error searching similar: {e}")

    if not all_error_info:
        print("No failed CI runs found across any provider.")
        github_actions.post_pr_comment(
            REPO, PR_NUMBER,
            "## CI Failure Triage Report\n\n"
            "No failed CI runs found for this PR.\n\n"
            "_Generated by CI Triage Bot_"
        )
        return

    # 3. Get PR diff
    print("Fetching PR diff...")
    diff = github_actions.get_pr_diff(REPO, PR_NUMBER, MAX_DIFF_CHARS)

    # 4. Analyze with Claude
    print("Analyzing with Claude...")
    analysis = analyze_with_claude(all_error_info, all_similar, diff, PR_NUMBER)

    # 5. Post comment
    comment = format_comment(PR_NUMBER, all_runs, all_error_info, analysis, all_similar)
    github_actions.post_pr_comment(REPO, PR_NUMBER, comment)

    print("Triage complete.")


if __name__ == "__main__":
    main()
